services:
  # Web service
  - type: web
    name: ambp
    env: docker
    image: hafidzduddin/ambp:latest
    autoDeploy: true
    healthCheckPath: /health
    scaling:
      minInstances: 0
      maxInstances: 1
      targetMemoryPercent: 90
      targetCPUPercent: 90