services:
  # Web service
  - type: web
    name: ambp
    env: docker
    image: hafidzduddin/ambp:latest
    autoDeploy: true
    healthCheckPath: /health
    scaling:
      minInstances: 0
      maxInstances: 1
      targetMemoryPercent: 90
      targetCPUPercent: 90
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: SECRET_KEY
        sync: false  # Use Supabase Legacy JWT Secret
      - key: GOOGLE_SHEET_ID
        sync: false
      - key: GOOGLE_CREDS_JSON
        sync: false
      - key: APP_URL
        fromService:
          name: ambp
          type: web
          property: url