name: Build and Deploy

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Clear cache (force first build)
        run: |
          rm -rf /tmp/.buildx-cache || true
          echo "Cache cleared to force first build behavior"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Check if this is first build
        id: first-build
        run: |
          if [ ! -d "/tmp/.buildx-cache" ]; then
            echo "first_build=true" >> $GITHUB_OUTPUT
          else
            echo "first_build=false" >> $GITHUB_OUTPUT
          fi

      - name: Restore Docker layer cache
        uses: actions/cache@v3
        id: docker-cache
        with:
          path: /tmp/.buildx-cache
          key: buildx-cache-${{ github.ref_name }}-${{ github.sha }}
          restore-keys: |
            buildx-cache-${{ github.ref_name }}-
            buildx-cache-

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/ambp:latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max
          build-args: |
            BUILDKIT_INLINE_CACHE=1
          no-cache: ${{ steps.first-build.outputs.first_build == 'true' }}

      - name: Move cache for future builds
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Render
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.RENDER_SERVICE_ID }}
          api-key: ${{ secrets.RENDER_API_KEY }}